### ISSUE TITLE
Refactoring the  Repo Branch Structure

### ISSUE THREAD

**Issue by copasetickid** [flatiron-labs/wiki#1]
The current process creates more blockers and overheard for a project than the solution we are trying to solve as `develop` is acting as fake `master` branch, in which we are updating code in two branches before it reaches a server and  reverse(force-pushing) pushing code to its central destination. (i.e. Github & our local branches)

Currently `develop` (which is also used to push to staging env.) is 231 commits ahead of the `master` and has features in it that aren't ready to put into `master` as well because they haven't been accepted by tested / QA'd process. This process seems over-engineered when the `master` branch should always have the code  that's been tested / QA'd / bugs because if there is a bug or a feature that needs go out to production it can't because the shadow (`develop`) branch is holding up its release process (because of the factors stated in the previous sentence). 

This, in time will lead to following conflicts below (such of which have already occurred):  
* conflicts, and unstable code in both in two places instead of one because if my feature passes QA, goes into `develop` and then into `master` but if there is a bugs it needs to be reversed (pushed) in two places
* there will be confusion over which features / bug fixes are in the `master` branch & various server env because of the because there's no clarity over what's out and live versus what hasn't made its way back into `master` and leads to various cherry-picks that will populate the git history.
* confusion when  on-boarding a developer to the team as a typical workflow whether your working alone or on a team is start a new app or branch off from   `master` as it keeps this things clean locally & remotely, 
* force pushing the latest of the `develop` branch to `master`, even though it seems like its in good faith, but its really increasing / spreading potentially code with bugs into than 1 more branch at a time 
* Force pushing to master is a bad habit to start as you run the risk of force pushing the wrong branch into `master`
* its as if we were fighting Git by having two `master` branches instead of creating a `staging` branch off a `master` to use when we want to put code on a staging env; instead of the having to wait 
* `develop` holds up the accuracy of the state of `master` has external factors run the high risk of testing which allows it to go 'x' amount of days before `master` is updated with the latest

*A solution to this  problem(s) going forward for future applications: only have one primary  branch which is `master`*

Instead of merging the `feature` branches into the `develop` (which has taken weeks for it to get back into `master`) we will be to have `feature` branches go from typical code review process but instead get merged only into the `master` branch. This git team workflow  eliminates  the following roadblocks when a team is  working on an application

*  Bug fixes can be rolled out sooner
*  Not releasing features that aren't ready for a server env.
*  Eliminates the need to cherry-pick
*  Keeps the git history clean 
*  Not worrying about features getting back into master because that they've been tested /QA'd
*  Standard convention is to work from `master`, its how Git was designed, what Github defaults to, and what many CI products configurations work off from as well
* Can easily make production; staging; & bug -releases branches because of the state of application is clear known as it origins are the `master` branch 
* We can make use of tags from Git and the release feature from Github to document what features and bugs went out in releases to staging &/or production

**Comment by adamjonas** [comment]
We ended up making this change way back in March. Closing.
